/**
 * SEO Sitemap Paths — Generated by scripts/generate-seo-pages.ts
 *
 * This file is auto-generated when you run `npm run generate:seo`.
 * It provides the list of programmatic SEO page paths for sitemap.ts.
 * If this file doesn't exist, the sitemap gracefully falls back to
 * an empty array (no pSEO pages in sitemap).
 *
 * DO NOT EDIT MANUALLY — regenerate with `npm run generate:seo`.
 */

export const SEO_SITEMAP_PATHS: string[] = [];
