/**
 * sitemap.ts — Auto-generated sitemap.xml for search engine discovery.
 *
 * WHY THIS EXISTS:
 * Search engines use sitemap.xml to discover pages they should crawl and index.
 * Without it, crawlers may miss new pages or crawl at a slower cadence. This
 * is a standard SEO requirement for any web product.
 *
 * BASE URL:
 * Reads from siteConfig.siteUrl which comes from NEXT_PUBLIC_APP_URL env var
 * (with .trim() to strip trailing whitespace/newlines — a common Vercel env
 * entry mistake). Falls back to the Vercel preview URL, then localhost.
 *
 * HOW TO CUSTOMIZE:
 * Add or remove paths from the `paths` array below to match your product's
 * routes. Common additions: /generate, /gallery, /studio, /about, /vs/* pages.
 *
 * PROGRAMMATIC SEO PAGES:
 * The sitemap automatically includes all pages from three systems:
 *   1. /vs/[competitor], /for/[audience], /use-cases/[use-case] from
 *      src/config/seo-pages.ts (new structured SEO page system)
 *   2. /best/[slug] and legacy /vs/[slug] from src/lib/seo-pages.ts
 *      (generated from seo-config.json)
 *   3. Paths from scripts/generate-seo-pages.ts if that generator has been run
 *
 * ADDED TO TEMPLATE: 2026-04-08 (steel-circuit-4738) — required for all clones.
 * Previously only some fleet repos had this; now ships in the template so every
 * new clone starts with proper sitemap coverage.
 */

import type { MetadataRoute } from "next";
import { siteConfig } from "@/config/site";
import { SEO_PAGES_CONFIG } from "@/config/seo-pages";

/**
 * Programmatic SEO page paths generated by scripts/generate-seo-pages.ts.
 * If the file doesn't exist (generator hasn't been run), this resolves to
 * an empty array so the sitemap still works for fresh template clones.
 */
let seoSitemapPaths: string[] = [];
try {
  // Dynamic require so the build doesn't fail when the file doesn't exist yet.
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const seoModule = require("@/lib/seo-sitemap-paths");
  seoSitemapPaths = seoModule.SEO_SITEMAP_PATHS || [];
} catch {
  // File doesn't exist yet — generator hasn't been run. That's fine.
}

/**
 * Programmatic SEO paths from seo-pages.ts config (/best/[slug] and legacy /vs/[slug]).
 * These are generated from seo-config.json data at build time. Every clone that
 * has industries/competitors in seo-config.json gets these pages automatically.
 */
let programmaticSeoPaths: string[] = [];
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { getSeoPageConfig } = require("@/lib/seo-pages");
  const seoPageConfig = getSeoPageConfig();
  const bestPaths = (seoPageConfig.bestForPages || []).map(
    (p: { slug: string }) => `/best/${p.slug}`
  );
  const legacyVsPaths = (seoPageConfig.vsPages || []).map(
    (p: { slug: string }) => `/vs/${p.slug}`
  );
  programmaticSeoPaths = [...bestPaths, ...legacyVsPaths];
} catch {
  // seo-pages module not available — no programmatic SEO pages.
}

/**
 * Strip trailing slash from base URL to avoid double-slash in generated URLs.
 * NEXT_PUBLIC_APP_URL is already trimmed in site.ts via .trim(), so this just
 * handles the optional trailing slash case.
 */
const BASE_URL = siteConfig.siteUrl.replace(/\/$/, "");

/**
 * Core pages that every SaaS clone ships with.
 *
 * HOW TO EXTEND:
 * When you add product-specific routes (e.g. /generate, /studio, /gallery),
 * add them here so search engines discover them at launch, not months later.
 *
 * WHY LEGAL PAGES ARE INCLUDED:
 * Privacy policy and terms of service improve trust signals in SERPs.
 * Some directories (Toolify, AlternativeTo) also require verified legal pages
 * before listing your product.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();

  const paths = [
    "",           // homepage — highest priority
    "/pricing",   // conversion-critical
    "/login",     // user acquisition
    "/privacy",
    "/terms-of-service",
    "/refund-policy",
  ];

  /**
   * Core product pages — highest priority for crawlers.
   */
  const coreSitemapEntries = paths.map((path) => ({
    url: `${BASE_URL}${path}`,
    lastModified,
    changeFrequency: "weekly" as const,
    priority:
      path === "" ? 1.0
      : path === "/pricing" ? 0.9
      : path.startsWith("/privacy") || path.startsWith("/terms") || path.startsWith("/refund") ? 0.5
      : 0.8,
  }));

  /**
   * New structured SEO pages from src/config/seo-pages.ts.
   * These target three keyword patterns:
   *   /vs/[competitor]         — "[Product] vs [Competitor]" buying intent
   *   /for/[audience]          — "Best AI [Tool] for [Audience]" research intent
   *   /use-cases/[use-case]    — "How to [Use Case] with AI" problem-solving intent
   *
   * Priority 0.7: above legal pages (0.5) but below core product pages (0.8+).
   * This reflects their value as long-tail traffic drivers that support the
   * primary conversion pages.
   */
  const newSeoCompetitorEntries: MetadataRoute.Sitemap =
    SEO_PAGES_CONFIG.competitors.map((competitorEntry) => ({
      url: `${BASE_URL}/vs/${competitorEntry.slug}`,
      lastModified,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    }));

  const newSeoAudienceEntries: MetadataRoute.Sitemap =
    SEO_PAGES_CONFIG.audiences.map((audienceEntry) => ({
      url: `${BASE_URL}/for/${audienceEntry.slug}`,
      lastModified,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    }));

  const newSeoUseCaseEntries: MetadataRoute.Sitemap =
    SEO_PAGES_CONFIG.useCases.map((useCaseEntry) => ({
      url: `${BASE_URL}/use-cases/${useCaseEntry.slug}`,
      lastModified,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    }));

  /**
   * Legacy SEO paths from scripts/generate-seo-pages.ts (if run).
   */
  const seoSitemapEntries = seoSitemapPaths.map((seoPath) => ({
    url: `${BASE_URL}${seoPath}`,
    lastModified,
    changeFrequency: "monthly" as const,
    priority: seoPath === "/seo" ? 0.7 : 0.6,
  }));

  /**
   * Legacy programmatic SEO from seo-config.json (/best/ and old /vs/ pages).
   */
  const programmaticSeoEntries = programmaticSeoPaths.map((seoPath) => ({
    url: `${BASE_URL}${seoPath}`,
    lastModified,
    changeFrequency: "monthly" as const,
    priority: 0.7,
  }));

  /**
   * Deduplicate URLs — the new /vs/ pages from seo-pages.ts config may overlap
   * with legacy /vs/ pages from seo-config.json. Use a Set to ensure each URL
   * appears exactly once in the final sitemap.
   */
  const allEntries = [
    ...coreSitemapEntries,
    ...newSeoCompetitorEntries,
    ...newSeoAudienceEntries,
    ...newSeoUseCaseEntries,
    ...seoSitemapEntries,
    ...programmaticSeoEntries,
  ];

  const seenUrls = new Set<string>();
  const deduplicatedEntries: MetadataRoute.Sitemap = [];
  for (const entry of allEntries) {
    if (!seenUrls.has(entry.url)) {
      seenUrls.add(entry.url);
      deduplicatedEntries.push(entry);
    }
  }

  return deduplicatedEntries;
}
